//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Time { get; set; }
        public Nullable<int> Year { get; set; }
        public string MovieLink { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Rate { get; set; }
        public int Viewed { get; set; }
        public bool Status { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
    }
}
